apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: %APP_NAME%-certificate
  namespace: %KUBERNETES_NAMESPACE%
spec:
  secretName: %APP_NAME%-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h
  renewBefore: 720h
  subject:
    organizations:
    - %CERTIFICATE_ORGANIZATION%
  dnsNames: 
%CERTIFICATE_DNS_NAMES%
  privateKey:
    rotationPolicy: Always  
