apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: %APP_NAME%
  namespace: %KUBERNETES_NAMESPACE%
  annotations:
    alb.networking.azure.io/alb-namespace: kube-system
    alb.networking.azure.io/alb-name: alb-controller
spec:
  gatewayClassName: azure-alb-external
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: %CERTIFICATE_HOST%-tls