name: Build and Deploy
on:
  push
env:
  APP_NAME: public-gateway
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  AZURE_GROUP_KUBERNETES: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES }} 
  AZURE_GROUP_KUBERNETES_ASSETS: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES_ASSETS }} 
  AZURE_GROUP_DNS: ${{ vars.AZURE_RESOURCE_GROUP_DNS }} 
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  KUBERNETES_CLUSTER: ${{ github.ref == 'refs/heads/master' && vars.PRODUCTION_KUBERNETES_CLUSTER || vars.STAGING_KUBERNETES_CLUSTER }}
  KUBERNETES_NODEPOOL_COMPUTE: cpu
  KUBERNETES_NAMESPACE: apps
  CERTIFICATE_ORGANIZATION: Nano-Core
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        shell: pwsh
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;
          az aks get-credentials -g $env:AZURE_GROUP_KUBERNETES -n $env:KUBERNETES_CLUSTER -o none;

      - name: Deploy Gateway And Load Balancer
        shell: pwsh
        run: |
          $env:VNET_NAME = az network vnet list -g $env:AZURE_GROUP_KUBERNETES_ASSETS --query [0].name -o tsv;
          $env:ALB_SUBNET_ID = az network vnet subnet show -n aks-subnet-alb -g $env:AZURE_GROUP_KUBERNETES_ASSETS --vnet-name $env:VNET_NAME --query id -o tsv;

          $zones = az network dns zone list -g $env:AZURE_GROUP_DNS | ConvertFrom-Json;
 
          $env:CERTIFICATE_DNS_NAMES = @(
              foreach ($zone in $zones) {
          @"
              - $($zone.name),
                *.$($zone.name)
          "@
              }
          ) -join "`n";

          Get-Content .kubernetes/application-load-balancer.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/application-load-balancer.tmp.yaml;
          Get-Content .kubernetes/gateway.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/gateway.tmp.yaml;
          Get-Content .kubernetes/certificate.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/certificate.tmp.yaml;
          
          $command = @"
              set -eu

              kubectl apply -f application-load-balancer.tmp.yaml || exit 1
              kubectl apply -f gateway.tmp.yaml || exit 2
              kubectl apply -f certificate.tmp.yaml || exit 3
          "@;

          $result = az aks command invoke `
              -g $env:AZURE_GROUP_KUBERNETES `
              -n $env:KUBERNETES_CLUSTER `
              --file .kubernetes/application-load-balancer.tmp.yaml `
              --file .kubernetes/gateway.tmp.yaml `
              --file .kubernetes/certificate.tmp.yaml `
              --command $command `
              --output json | ConvertFrom-Json;

          echo $result;

          if ($result.exitCode -ne 0)
          {
              throw "error";
          }

      - name: Create DNS CNAME Records
        shell: pwsh
        run: |
          az config set extension.dynamic_install_allow_preview=true;

          $env:ALB_NAME = az network alb list -g $env:AZURE_GROUP_KUBERNETES_ASSETS --query [0].name -o tsv;
          $env:ALB_FQDN = az network alb frontend list -g $env:AZURE_GROUP_KUBERNETES_ASSETS --alb-name $env:ALB_NAME --query [0].fqdn -o tsv;

          $zones = az network dns zone list -g $env:AZURE_GROUP_DNS | ConvertFrom-Json;

          foreach ($zone in $zones) 
          {
              $recordExists = az network dns record-set cname show `
                  -g $env:AZURE_GROUP_DNS `
                  -z $zone.name `
                  -n "*" `
                  --query "name" `
                  -o tsv `
                  --only-show-errors;

              if (-not $recordExists)
              {
                  az network dns record-set cname create `
                      -g $env:AZURE_GROUP_DNS `
                      -z $zone.name `
                      -n "*" `
                      --ttl 3600;

                  az network dns record-set cname set-record `
                      -g $env:AZURE_GROUP_DNS `
                      -z $zone.name `
                      -n "*" `
                      -c $env:ALB_FQDN;
              }



              # az network dns record-set cname create `
              #     -g $env:AZURE_GROUP_DNS `
              #     -z $($zone.name) `
              #     -n "*" `
              #     --ttl 3600 `
              #     --if-none-match "*" -o none;

              # az network dns record-set cname set-record `
              #     -g $env:AZURE_GROUP_DNS `
              #     -z $($zone.name) `
              #     -n "*" `
              #     -c $env:ALB_FQDN -o none;
          }

          if ($LastExitCode -ne 0)
          { 
              throw "error";
          }
 
      - name: GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false